#!/usr/bin/env ruby
Dir.chdir __dir__
require 'rubygems'
require 'bundler/setup'
require 'dotenv'
Dotenv.load

# Message the current dev of the day on HipChat.
# To use: message_dev_of_day '%s is the dev of the day!'

require 'hipchat'

HIPCHAT_TOKEN = ENV['HIPCHAT_TOKEN'] || raise('HIPCHAT_TOKEN required')
hipchat = HipChat::Client.new(HIPCHAT_TOKEN, :api_version => 'v2')

mention_name = `./dev_of_day_hipchat`
hipchat['Developers'].send('Dev of the Day', sprintf(ARGV[0], "@#{mention_name}", :message_format => 'text'))
